{% set name = "addfips" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/addfips-{{ version }}.tar.gz
  sha256: 1f397c940dd25eb3524c57c3e2182fed4d7d01a1184bcd0c5932c127fff71266

build:
  number: 0
  noarch: python
  entry_points:
    - addfips=addfips.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - importlib_resources >=2.0.1
    - python >=3.6

test:
  imports:
    - addfips
  commands:
    - pip check
    - addfips --help
  requires:
    - pip

about:
  home: https://github.com/fitnr/addfips/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: AddFIPS is a tool for adding state or county FIPS codes to files that contain just the names of those geographies.

  description: |
    AddFIPS is a tool for adding state or county FIPS codes to files that
    contain just the names of those geographies. FIPS codes are the official
    ID numbers of places in the US. They're invaluable for matching data from
    different sources.
  doc_url: https://github.com/fitnr/addfips/
  dev_url: https://github.com/fitnr/addfips/

extra:
  recipe-maintainers:
    - zaneselvans
